name: build
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  win-build:
    runs-on: windows-latest
    strategy:
      matrix:
        mode: [onedir, onefile]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt -c constraints.txt

      - name: PyInstaller build (${{ matrix.mode }})
        run: |
          if ('${{ matrix.mode }}' -eq 'onedir') {
            pyinstaller .src\full_pipline_gui.py `
              --onedir -y --clean --console `
              --name main `
              --runtime-hook rthooks\rt_gdal_env.py `
              --collect-all rasterio `
              --collect-data pyproj `
              --log-level=WARN
          } else {
            pyinstaller .src\full_pipline_gui.py `
              --onefile -y --clean --console `
              --name main `
              --runtime-hook rthooks\rt_gdal_env.py `
              --collect-all rasterio `
              --collect-data pyproj `
              --log-level=WARN
          }

      - name: Smoke test
        shell: pwsh
        env:
          APP_NO_PAUSE: "1"
        run: |
          $exe = if ('${{ matrix.mode }}' -eq 'onefile') { '.\dist\main.exe' } else { '.\dist\main\main.exe' }
          & $exe | Select-String "GDAL from rasterio" | Out-Null


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-${{ matrix.mode }}-windows
          path: |
            dist/main.exe
            dist/main/**
          if-no-files-found: ignore
          retention-days: 7
