name: build
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  win-build:
    runs-on: windows-latest
    strategy:
      matrix:
        mode: [onedir, onefile]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt 

      - name: PyInstaller build (${{ matrix.mode }})
        run: |
          if ('${{ matrix.mode }}' -eq 'onedir') {
            pyinstaller --paths=src `
              --onedir -y --clean --console `
              --name main `
              --runtime-hook rthooks\rt_gdal_env.py `
              --add-data "config;config" `
              --collect-all rasterio `
              --collect-data pyproj `
              --log-level=WARN `
              .\src\__main__.py
          } else {
            pyinstaller --paths=src `
              --onefile -y --clean --console `
              --name main `
              --runtime-hook rthooks\rt_gdal_env.py `
              --add-data "config;config" `
              --collect-all rasterio `
              --collect-data pyproj `
              --log-level=WARN `
              .\src\__main__.py
          }


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-${{ matrix.mode }}-windows
          path: |
            dist/main.exe
            dist/main/**
          if-no-files-found: ignore
          retention-days: 7
